decompose:
  width: 15
  height: 13
  widthFactor: 0.10
  heightFactor: 0.10
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
spring:
  security:
    user:
      name: user
      password: pass
      roles:
      - ACTUATOR
